Add profile config api
ichala/short-let-api pull request #37
Opened 2022-09-21 15:05 UTC by aimalamiri

## Add update profile API

PATCH `/profile/update`

`response`

```json
{
    "updated": {
        "id": 18,
        "first_name": "Aimal",
        "last_name": "Amiri",
        "role": "admin",
        "email": "meaimal@hotmail.com",
        "password_digest": "$2a$12$HzGUaR6OZKSvomMUawSmluKSHIEaSKMtdzdg/TQZiMOlaWXglR.3u",
        "created_at": "2022-09-19T15:05:26.060Z",
        "updated_at": "2022-09-21T15:00:29.492Z"
    }
}

```

closes #11

2022-09-21 15:14 UTC, ichala requested changes
🛑 REQUIRED CHANGES 🛑


@aimalamiri great job ,
- [ ] there's an error should be handled which is **_if the new provided email exist already_** 
- [x]  you need to consider handling the error of server error wich is 

```Ruby
if user.update(profile_params)
render json: { updated: current_user } 
else
render json: { error: current_user } , status: :not_implemented
end
```

2022-09-21 15:24 UTC, aimalamiri commented
> 🛑 REQUIRED CHANGES 🛑
> 
> @aimalamiri great job ,
> 
> * [x]  there's an error should be handled which is **_if the new provided email exist already_**
> * [x]   you need to consider handling the error of server error wich is
> 
> ```ruby
> if user.update(profile_params)
> render json: { updated: current_user } 
> else
> render json: { error: current_user } , status: :not_implemented
> end
> ```

Tahnks for the tip. It's done.

2022-09-21 15:56 UTC, ichala commented
✅ Approved for me ✅

2022-09-21 15:57 UTC, ichala commented
✅ APPROVED FOR ME ✅

2022-09-22 11:29 UTC, d2ndjim commented on app/controllers/profile_controller.rb
> +end
Clean and Organized implementation 👍

2022-09-22 11:30 UTC, d2ndjim approved these changes
@aimalamiri 
### APPROVED ✔️ ✔️ ✔️

2022-09-22 12:20 UTC, aimalamiri commented on app/controllers/profile_controller.rb
> +end
Thank you 🙏

2022-09-22 12:22 UTC, EidHachem approved these changes
Great job @aimalamiri 

# Approved ✔️ 

It's time to merge 🎉

2022-09-22 12:34 UTC, ichala approved these changes

2022-09-22 16:21 UTC, merged